## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns = ['EIN', 'NAME'], axis = 1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [9]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
app_count = application_df['APPLICATION_TYPE'].value_counts()

In [10]:
application_df.dtypes

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

In [19]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = list(app_count[app_count<10].index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: APPLICATION_TYPE, dtype: int64

In [20]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
count_class = application_df['CLASSIFICATION'].value_counts()

In [21]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x >1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [23]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(count_class[count_class <500].index)
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [25]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
df_dummies = pd.get_dummies(application_df)

In [26]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = df_dummies['IS_SUCCESSFUL']
X = df_dummies.drop(['IS_SUCCESSFUL'], axis=1)
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=45)

In [27]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [30]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
input_ft = len(X_train_scaled[0])
f_nodes = 6
s_nodes = 2
nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units= f_nodes, activation="relu", input_dim=input_ft))
# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=s_nodes, activation="relu", input_dim=input_ft))
# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 6)                 294

 dense_1 (Dense)             (None, 2)                 14

 dense_2 (Dense)             (None, 1)                 3

=================================================================
Total params: 311
Trainable params: 311
Non-trainable params: 0
_________________________________________________________________

In [31]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [32]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 783us/step - loss: 0.6389 - accuracy: 0.6425
Epoch 2/100
804/804 [==============================] - 1s 773us/step - loss: 0.5884 - accuracy: 0.6961
Epoch 3/100
804/804 [==============================] - 1s 809us/step - loss: 0.5796 - accuracy: 0.7021
Epoch 4/100
804/804 [==============================] - 1s 781us/step - loss: 0.5737 - accuracy: 0.7057
Epoch 5/100
804/804 [==============================] - 1s 772us/step - loss: 0.5650 - accuracy: 0.7222
Epoch 6/100
804/804 [==============================] - 1s 794us/step - loss: 0.5616 - accuracy: 0.7261
Epoch 7/100
804/804 [==============================] - 1s 780us/step - loss: 0.5607 - accuracy: 0.7263
Epoch 8/100
804/804 [==============================] - 1s 786us/step - loss: 0.5597 - accuracy: 0.7271
Epoch 9/100
804/804 [==============================] - 1s 790us/step - loss: 0.5588 - accuracy: 0.7268
Epoch 10/100
804/804 [==============================] - 1s 807us/step - loss: 0.5581 - accuracy: 0.7273
Epoch 11/100
804/804 [==============================] - 1s 780us/step - loss: 0.5573 - accuracy: 0.7255
Epoch 12/100
804/804 [==============================] - 1s 783us/step - loss: 0.5564 - accuracy: 0.7270
Epoch 13/100
804/804 [==============================] - 1s 784us/step - loss: 0.5559 - accuracy: 0.7267
Epoch 14/100
804/804 [==============================] - 1s 780us/step - loss: 0.5555 - accuracy: 0.7263
Epoch 15/100
804/804 [==============================] - 1s 783us/step - loss: 0.5549 - accuracy: 0.7270
Epoch 16/100
804/804 [==============================] - 1s 769us/step - loss: 0.5547 - accuracy: 0.7268
Epoch 17/100
804/804 [==============================] - 1s 775us/step - loss: 0.5544 - accuracy: 0.7266
Epoch 18/100
804/804 [==============================] - 1s 786us/step - loss: 0.5540 - accuracy: 0.7268
Epoch 19/100
804/804 [==============================] - 1s 807us/step - loss: 0.5539 - accuracy: 0.7265
Epoch 20/100
804/804 [==============================] - 1s 770us/step - loss: 0.5536 - accuracy: 0.7269
Epoch 21/100
804/804 [==============================] - 1s 770us/step - loss: 0.5532 - accuracy: 0.7274
Epoch 22/100
804/804 [==============================] - 1s 765us/step - loss: 0.5529 - accuracy: 0.7272
Epoch 23/100
804/804 [==============================] - 1s 798us/step - loss: 0.5526 - accuracy: 0.7267
Epoch 24/100
804/804 [==============================] - 1s 790us/step - loss: 0.5528 - accuracy: 0.7276
Epoch 25/100
804/804 [==============================] - 1s 835us/step - loss: 0.5524 - accuracy: 0.7268
Epoch 26/100
804/804 [==============================] - 1s 801us/step - loss: 0.5523 - accuracy: 0.7265
Epoch 27/100
804/804 [==============================] - 1s 827us/step - loss: 0.5520 - accuracy: 0.7275
Epoch 28/100
804/804 [==============================] - 1s 794us/step - loss: 0.5518 - accuracy: 0.7271
Epoch 29/100
804/804 [==============================] - 1s 780us/step - loss: 0.5518 - accuracy: 0.7275
Epoch 30/100
804/804 [==============================] - 1s 782us/step - loss: 0.5518 - accuracy: 0.7278
Epoch 31/100
804/804 [==============================] - 1s 797us/step - loss: 0.5516 - accuracy: 0.7273
Epoch 32/100
804/804 [==============================] - 1s 792us/step - loss: 0.5516 - accuracy: 0.7267
Epoch 33/100
804/804 [==============================] - 1s 768us/step - loss: 0.5517 - accuracy: 0.7266
Epoch 34/100
804/804 [==============================] - 1s 775us/step - loss: 0.5513 - accuracy: 0.7271
Epoch 35/100
804/804 [==============================] - 1s 781us/step - loss: 0.5512 - accuracy: 0.7271
Epoch 36/100
804/804 [==============================] - 1s 784us/step - loss: 0.5514 - accuracy: 0.7269
Epoch 37/100
804/804 [==============================] - 1s 775us/step - loss: 0.5508 - accuracy: 0.7272
Epoch 38/100
804/804 [==============================] - 1s 780us/step - loss: 0.5509 - accuracy: 0.7271
Epoch 39/100
804/804 [==============================] - 1s 783us/step - loss: 0.5509 - accuracy: 0.7268
Epoch 40/100
804/804 [==============================] - 1s 780us/step - loss: 0.5503 - accuracy: 0.7270
Epoch 41/100
804/804 [==============================] - 1s 778us/step - loss: 0.5502 - accuracy: 0.7269
Epoch 42/100
804/804 [==============================] - 1s 774us/step - loss: 0.5499 - accuracy: 0.7277
Epoch 43/100
804/804 [==============================] - 1s 760us/step - loss: 0.5501 - accuracy: 0.7264
Epoch 44/100
804/804 [==============================] - 1s 780us/step - loss: 0.5497 - accuracy: 0.7274
Epoch 45/100
804/804 [==============================] - 1s 764us/step - loss: 0.5499 - accuracy: 0.7264
Epoch 46/100
804/804 [==============================] - 1s 770us/step - loss: 0.5498 - accuracy: 0.7274
Epoch 47/100
804/804 [==============================] - 1s 776us/step - loss: 0.5494 - accuracy: 0.7274
Epoch 48/100
804/804 [==============================] - 1s 790us/step - loss: 0.5498 - accuracy: 0.7265
Epoch 49/100
804/804 [==============================] - 1s 778us/step - loss: 0.5497 - accuracy: 0.7283
Epoch 50/100
804/804 [==============================] - 1s 797us/step - loss: 0.5495 - accuracy: 0.7286
Epoch 51/100
804/804 [==============================] - 1s 785us/step - loss: 0.5494 - accuracy: 0.7264
Epoch 52/100
804/804 [==============================] - 1s 782us/step - loss: 0.5492 - accuracy: 0.7259
Epoch 53/100
804/804 [==============================] - 1s 785us/step - loss: 0.5497 - accuracy: 0.7264
Epoch 54/100
804/804 [==============================] - 1s 776us/step - loss: 0.5494 - accuracy: 0.7278
Epoch 55/100
804/804 [==============================] - 1s 777us/step - loss: 0.5493 - accuracy: 0.7273
Epoch 56/100
804/804 [==============================] - 1s 784us/step - loss: 0.5490 - accuracy: 0.7271
Epoch 57/100
804/804 [==============================] - 1s 781us/step - loss: 0.5494 - accuracy: 0.7259
Epoch 58/100
804/804 [==============================] - 1s 796us/step - loss: 0.5492 - accuracy: 0.7263
Epoch 59/100
804/804 [==============================] - 1s 778us/step - loss: 0.5488 - accuracy: 0.7273
Epoch 60/100
804/804 [==============================] - 1s 797us/step - loss: 0.5491 - accuracy: 0.7273
Epoch 61/100
804/804 [==============================] - 1s 774us/step - loss: 0.5489 - accuracy: 0.7267
Epoch 62/100
804/804 [==============================] - 1s 789us/step - loss: 0.5488 - accuracy: 0.7269
Epoch 63/100
804/804 [==============================] - 1s 787us/step - loss: 0.5488 - accuracy: 0.7264
Epoch 64/100
804/804 [==============================] - 1s 774us/step - loss: 0.5487 - accuracy: 0.7276
Epoch 65/100
804/804 [==============================] - 1s 772us/step - loss: 0.5489 - accuracy: 0.7274
Epoch 66/100
804/804 [==============================] - 1s 771us/step - loss: 0.5487 - accuracy: 0.7268
Epoch 67/100
804/804 [==============================] - 1s 788us/step - loss: 0.5485 - accuracy: 0.7266
Epoch 68/100
804/804 [==============================] - 1s 791us/step - loss: 0.5486 - accuracy: 0.7278
Epoch 69/100
804/804 [==============================] - 1s 780us/step - loss: 0.5483 - accuracy: 0.7275
Epoch 70/100
804/804 [==============================] - 1s 764us/step - loss: 0.5488 - accuracy: 0.7275
Epoch 71/100
804/804 [==============================] - 1s 759us/step - loss: 0.5482 - accuracy: 0.7277
Epoch 72/100
804/804 [==============================] - 1s 771us/step - loss: 0.5485 - accuracy: 0.7272
Epoch 73/100
804/804 [==============================] - 1s 775us/step - loss: 0.5485 - accuracy: 0.7276
Epoch 74/100
804/804 [==============================] - 1s 799us/step - loss: 0.5486 - accuracy: 0.7278
Epoch 75/100
804/804 [==============================] - 1s 778us/step - loss: 0.5486 - accuracy: 0.7277
Epoch 76/100
804/804 [==============================] - 1s 814us/step - loss: 0.5486 - accuracy: 0.7275
Epoch 77/100
804/804 [==============================] - 1s 781us/step - loss: 0.5482 - accuracy: 0.7282
Epoch 78/100
804/804 [==============================] - 1s 785us/step - loss: 0.5484 - accuracy: 0.7285
Epoch 79/100
804/804 [==============================] - 1s 796us/step - loss: 0.5482 - accuracy: 0.7273
Epoch 80/100
804/804 [==============================] - 1s 798us/step - loss: 0.5482 - accuracy: 0.7278
Epoch 81/100
804/804 [==============================] - 1s 806us/step - loss: 0.5484 - accuracy: 0.7280
Epoch 82/100
804/804 [==============================] - 1s 808us/step - loss: 0.5480 - accuracy: 0.7281
Epoch 83/100
804/804 [==============================] - 1s 821us/step - loss: 0.5483 - accuracy: 0.7284
Epoch 84/100
804/804 [==============================] - 1s 803us/step - loss: 0.5482 - accuracy: 0.7280
Epoch 85/100
804/804 [==============================] - 1s 793us/step - loss: 0.5479 - accuracy: 0.7283
Epoch 86/100
804/804 [==============================] - 1s 779us/step - loss: 0.5481 - accuracy: 0.7292
Epoch 87/100
804/804 [==============================] - 1s 779us/step - loss: 0.5481 - accuracy: 0.7286
Epoch 88/100
804/804 [==============================] - 1s 779us/step - loss: 0.5483 - accuracy: 0.7275
Epoch 89/100
804/804 [==============================] - 1s 788us/step - loss: 0.5482 - accuracy: 0.7290
Epoch 90/100
804/804 [==============================] - 1s 782us/step - loss: 0.5482 - accuracy: 0.7281
Epoch 91/100
804/804 [==============================] - 1s 782us/step - loss: 0.5482 - accuracy: 0.7282
Epoch 92/100
804/804 [==============================] - 1s 791us/step - loss: 0.5479 - accuracy: 0.7286
Epoch 93/100
804/804 [==============================] - 1s 801us/step - loss: 0.5479 - accuracy: 0.7287
Epoch 94/100
804/804 [==============================] - 1s 773us/step - loss: 0.5481 - accuracy: 0.7283
Epoch 95/100
804/804 [==============================] - 1s 786us/step - loss: 0.5480 - accuracy: 0.7292
Epoch 96/100
804/804 [==============================] - 1s 808us/step - loss: 0.5480 - accuracy: 0.7283
Epoch 97/100
804/804 [==============================] - 1s 782us/step - loss: 0.5479 - accuracy: 0.7285
Epoch 98/100
804/804 [==============================] - 1s 795us/step - loss: 0.5480 - accuracy: 0.7286
Epoch 99/100
804/804 [==============================] - 1s 802us/step - loss: 0.5480 - accuracy: 0.7283
Epoch 100/100
804/804 [==============================] - 1s 781us/step - loss: 0.5477 - accuracy: 0.7287

In [37]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/8575 - 0s - loss: 0.5578 - acc: 0.7263
Loss: 0.557812534073699, Accuracy: 0.7262973785400391

In [35]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save('AlphabetSoupCharity.h5')